# Generated by Django 5.2.5 on 2025-08-20 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(-5),
                ],
            ),
        ),
    ]
