# Generated by Django 5.2.5 on 2025-09-25 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(-5),
                ],
            ),
        ),
    ]
