# Generated by Django 5.2.5 on 2025-09-25 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0003_alter_rating_rating"),
        ("recipes", "0010_auto_20250914_1618"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("author", "recipe")},
        ),
    ]
