# Generated by Django 5.2.5 on 2025-09-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0004_rename_user_rating_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="comment",
        ),
    ]
