# Generated by Django 5.2.5 on 2025-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
