# Generated by Django 5.2.5 on 2025-08-12 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="api_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="ID from Spoonacular", null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="diet",
            field=models.CharField(
                choices=[
                    ("vegan", "Vegan"),
                    ("carnivore", "Carnivore"),
                    ("gluten_free", "Gluten-free"),
                    ("vegetarian", "Vegetarian"),
                    ("dairy_free", "Dairy-free"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(),
        ),
    ]
