# Generated by Django 5.2.5 on 2025-08-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_prep_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.TextField(),
        ),
    ]
