# Generated by Django 5.2.5 on 2025-08-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0002_recipe_api_id_alter_recipe_author_alter_recipe_diet_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="api_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="ID from Spoonacular", null=True
            ),
        ),
    ]
