# Generated by Django 5.2.5 on 2025-09-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_image_url_alter_recipe_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("main course", "Main Course"),
                    ("side dish", "Side Dish"),
                    ("dessert", "Dessert"),
                    ("appetizer", "Appetizer"),
                    ("salad", "Salad"),
                    ("bread", "Bread"),
                    ("breakfast", "Breakfast"),
                    ("soup", "Soup"),
                    ("beverage", "Beverage"),
                    ("sauce", "Sauce"),
                    ("marinade", "Marinade"),
                    ("fingerfood", "Fingerfood"),
                    ("snack", "Snack"),
                    ("drink", "Drink"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
    ]
