# Generated by Django 5.2.5 on 2025-09-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_category_alter_recipe_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
