# Generated by Django 5.2.5 on 2025-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tips",
            field=models.TextField(blank=True, null=True),
        ),
    ]
