# Generated by Django 5.2.5 on 2025-09-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_recipe_tips"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="tips",
            new_name="extra_tips",
        ),
    ]
