# Generated by Django 5.2.5 on 2025-09-14 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_recipe_category_alter_recipe_diet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("main course", "Main Course"),
                        ("side dish", "Side Dish"),
                        ("dessert", "Dessert"),
                        ("appetizer", "Appetizer"),
                        ("salad", "Salad"),
                        ("bread", "Bread"),
                        ("breakfast", "Breakfast"),
                        ("soup", "Soup"),
                        ("beverage", "Beverage"),
                        ("sauce", "Sauce"),
                        ("marinade", "Marinade"),
                        ("fingerfood", "Fingerfood"),
                        ("snack", "Snack"),
                        ("drink", "Drink"),
                    ],
                    default=list,
                    max_length=20,
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="diet",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("vegan", "Vegan"),
                        ("carnivore", "Carnivore"),
                        ("gluten_free", "Gluten-free"),
                        ("vegetarian", "Vegetarian"),
                        ("dairy_free", "Dairy-free"),
                        ("none", "None"),
                    ],
                    default=list,
                    max_length=20,
                ),
                size=None,
            ),
        ),
    ]
